Map<String, dynamic> iconsPokemon = {
  'grass': "lib/app/assets/icons/Vector.svg",
  'fire': "lib/app/assets/icons/fire.svg",
  'water': "lib/app/assets/icons/water.svg",
  'bug': "lib/app/assets/icons/bug.svg",
  'normal': "lib/app/assets/icons/normal.svg",
  'fighting': "lib/app/assets/icons/Vector.svg",
  'flying': "lib/app/assets/icons/fighting.svg",
  'poison': "lib/app/assets/icons/poison.svg",
  'ground': "lib/app/assets/icons/ground.svg",
  'rock': "lib/app/assets/icons/rock.svg",
  'ghost': "lib/app/assets/icons/Vector-2.svg",
  'steel': "lib/app/assets/icons/Vector-1.svg",
  'electric': "lib/app/assets/icons/electric.svg",
  'psychic': "lib/app/assets/icons/psychic.svg",
  'ice': "lib/app/assets/icons/ice.svg",
  'dragon': "lib/app/assets/icons/dragon.svg",
  'dark': "lib/app/assets/icons/Vector.svg",
  'fairy': "lib/app/assets/icons/fairy.svg",
};
